const pfpList = [
    "https://i.imgur.com/w4qWhUS.jpeg",
    "https://i.imgur.com/JrumECj.jpeg",
    "https://i.imgur.com/W3L38Bh.jpeg",
    "https://i.imgur.com/gGKv8ik.jpeg",
    "https://i.imgur.com/9IAS0YA.jpeg",
    "https://i.imgur.com/qK853Sp.jpeg",
    "https://i.imgur.com/Yctyymv.jpeg",
    "https://i.imgur.com/O2WH081.jpeg",
    "https://i.imgur.com/J0EEXOj.jpeg",
    "https://i.imgur.com/6gatE1J.jpeg",
    "https://i.imgur.com/kJ1aFHt.jpeg",
    "https://i.imgur.com/tUDhGia.jpeg",
    "https://i.imgur.com/pCuBf7j.jpeg",
    "https://i.imgur.com/5mimY9q.jpeg",
    "https://i.imgur.com/23n3OmD.jpeg",
    "https://i.imgur.com/xcPgTbp.jpeg",
    "https://i.imgur.com/yXbYjS3.jpeg",
    "https://i.imgur.com/gWR736E.jpeg",
    "https://i.imgur.com/Wb2GTAn.jpeg",
    "https://i.imgur.com/IWByGk3.jpeg",
    "https://i.imgur.com/q5KZG4d.jpeg",
    "https://i.imgur.com/cLw0AGj.jpeg",
    "https://i.imgur.com/3aADRut.jpeg",
    //   "https://randomuser.me/api/portraits/men/24.jpg",
    // "-----------------------------",
    "https://i.imgur.com/MSh35nH.png",
    "https://i.imgur.com/0HWaQMN.png",
    "https://i.imgur.com/DEUTPBA.png",
    "https://i.imgur.com/UKDwUca.png",
    "https://i.imgur.com/0iJl4E6.png",
    "https://i.imgur.com/5h5wcdE.png",
    "https://i.imgur.com/xlz5rVv.png",
    "https://i.imgur.com/iDsCkFa.png",
    "https://i.imgur.com/7Fk143f.png",
    "https://i.imgur.com/ZCu8jyt.png",
    "https://i.imgur.com/g6whbOI.png",
    "https://i.imgur.com/oZTPNyN.png",
    "https://i.imgur.com/F8Tv351.png",
    "https://i.imgur.com/G93qPzd.png",
    "https://i.imgur.com/NJTUpfQ.png",
    "https://i.imgur.com/tPpuOKK.png",
    "https://i.imgur.com/wwe6jYr.png",
    "https://i.imgur.com/rcKNOib.png",
    "https://i.imgur.com/LdIGjrT.png",
    "https://i.imgur.com/p8xfclj.png",
    "https://i.imgur.com/hqNHK9k.png",
    "https://i.imgur.com/tNlNmct.png",
    "https://i.imgur.com/ohaBq0K.png",
    "https://i.imgur.com/1pQ80FI.png",
    "https://i.imgur.com/OsCp998.png",
    "https://i.imgur.com/sBcnALy.png",
    "https://i.imgur.com/BxEboDc.png",
    "https://i.imgur.com/qmO0vWz.png",
    "https://i.imgur.com/EsrF7mW.png",
    // "-----------------------------",
    "https://i.imgur.com/yx64uub.png",
    "https://i.imgur.com/a7TGHEl.png",
    "https://i.imgur.com/msOuXRo.png",
    "https://i.imgur.com/1h8lmit.png",
    "https://i.imgur.com/Z25rqaY.png",
    "https://i.imgur.com/uR4v6HD.png",
    "https://i.imgur.com/kjzb4yv.png",
    "https://i.imgur.com/Qxq6hzv.png",
    "https://i.imgur.com/2q1GaVI.png",
    "https://i.imgur.com/IW9Ne9Y.png",
    "https://i.imgur.com/pyrEgyY.png",
    "https://i.imgur.com/gLloA3v.png",
    "https://i.imgur.com/zsiGtlv.png",
    "https://i.imgur.com/2VT9OlE.png",
    "https://i.imgur.com/wIPcLYQ.png",
    "https://i.imgur.com/azH5Fdk.png",
    "https://i.imgur.com/Gl6dDL4.png",
    "https://i.imgur.com/uCbBmRm.png",
    "https://i.imgur.com/TaxoQ4A.png",
    "https://i.imgur.com/yiZbAGv.png",
    "https://i.imgur.com/22NaYUx.png",
    "https://i.imgur.com/360AgYm.png",
    "https://i.imgur.com/syN5V41.png",
    "https://i.imgur.com/6ByMscj.png",
    "https://i.imgur.com/VucS2Hr.png",
    "https://i.imgur.com/QDA6eGI.png",
    "https://i.imgur.com/EtfaVux.png",
    "https://i.imgur.com/zmqwMU0.png",
    "https://i.imgur.com/OsxBTVE.png",
    "https://i.imgur.com/D9Botig.png",
    "https://i.imgur.com/EnQwMVp.png"
    ]
    
function pfp(){
    return pfpList[Math.floor(Math.random() * pfpList.length)];
}

module.exports = pfp

// todo: provide argument options like male, female, neutral